homepage: "https://skia.googlesource.com/skcms/+/master"
primary_contact: "kjlubick@chromium.org"
auto_ccs:
  - "mtklein@chromium.org"
  - "brianosman@google.com"
sanitizers:
 - address
 - memory
 - undefined
architectures:
  - x86_64
  - i386
