homepage: "https://github.com/google/skia"
primary_contact: "kjlubick@chromium.org"
auto_ccs:
  - "hcm@chromium.org"
  - "mtklein@google.com"
  - "reed@google.com"
  - "bsalomon@google.com"
sanitizers:
 - address
 - undefined
 - memory
help_url: "https://skia.org/dev/testing/fuzz"
