homepage: "https://developers.google.com/speed/webp/"
primary_contact: "jzern@google.com"
sanitizers:
- address
- undefined
- memory
auto_ccs:
- pascal.massimino@gmail.com
- vrabaud@google.com
- yguyon@google.com
vendor_ccs:
- cdiehl@mozilla.com
