homepage: "http://www.grpc.io/"
primary_contact: "yangg@google.com"
auto_ccs:
  - "guantaol@google.com"
  - "hcaseyal@google.com"
  - "juanlishen@google.com"
  - "mhaidry@google.com"
  - "roth@google.com"
  - "nnoble@google.com"
  - "sheenaqotj@google.com"
  - "vpai@google.com"
  - "yashkt@google.com"
fuzzing_engines:
  - libfuzzer
coverage_extra_args: -ignore-filename-regex=.*\.cache.*
