homepage: "https://www.openh264.org"
primary_contact: "huili2@cisco.com"
auto_ccs:
  - "guangwwa@cisco.com"
  - "sijchen@cisco.com"
  - "yanqian@cisco.com"
vendor_ccs:
  - "twsmith@mozilla.com"
  - "cdiehl@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
 - i386
 - x86_64
